# Generated by Django 3.1.2 on 2020-11-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidoP', models.CharField(max_length=35)),
                ('apellidoM', models.CharField(max_length=35)),
                ('nombre', models.CharField(max_length=35)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
    ]
